# Generated by Django 6.0.1 on 2026-01-31 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=200, verbose_name="Titre de la formation"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Budget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeContrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50, verbose_name="Nom du type de contrat"
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="departement",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departements_managed",
                to="employees.employe",
                verbose_name="Manager",
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="adresse",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="employe",
            name="date_naissance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="matricule",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Matricule",
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profil",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="poste",
            name="missions",
            field=models.TextField(blank=True, verbose_name="Missions"),
        ),
        migrations.AddField(
            model_name="poste",
            name="responsabilites",
            field=models.TextField(blank=True, verbose_name="Responsabilités"),
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("motif", models.TextField(verbose_name="Motif")),
                (
                    "justifie",
                    models.BooleanField(default=False, verbose_name="Justifié"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_conge",
                    models.CharField(
                        choices=[
                            ("ANNUEL", "Congé Annuel"),
                            ("MALADIE", "Congé Maladie"),
                            ("MATERNITE", "Maternité"),
                            ("SANS_SOLDE", "Sans Solde"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de congé",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("APPROUVE", "Approuvé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("motif", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "commentaire_manager",
                    models.TextField(blank=True, verbose_name="Commentaire Manager"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conges",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentRH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Titre du document"),
                ),
                (
                    "fichier",
                    models.FileField(upload_to="documents_rh/", verbose_name="Fichier"),
                ),
                (
                    "type_doc",
                    models.CharField(
                        choices=[
                            ("CONTRAT", "Contrat"),
                            ("CERTIFICAT", "Certificat"),
                            ("CV", "CV"),
                            ("PIECE_IDENTITE", "Pièce d'identité"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date d'évaluation")),
                ("score", models.IntegerField(verbose_name="Score / 100")),
                (
                    "commentaires",
                    models.TextField(blank=True, verbose_name="Commentaires"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "evaluateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_donnees",
                        to="employees.employe",
                        verbose_name="Évaluateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FichePaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.IntegerField(verbose_name="Mois")),
                ("annee", models.IntegerField(verbose_name="Année")),
                (
                    "salaire_base",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salaire de base"
                    ),
                ),
                (
                    "primes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Primes",
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Déductions",
                    ),
                ),
                (
                    "net_a_payer",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Net à payer"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="fiches_paie/",
                        verbose_name="Fiche de paie PDF",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches_paie",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InscriptionFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        default="Inscrit", max_length=50, verbose_name="Statut"
                    ),
                ),
                (
                    "attestation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attestations/",
                        verbose_name="Attestation",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.formation",
                        verbose_name="Formation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Objectif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("date_limite", models.DateField(verbose_name="Date limite")),
                ("realise", models.BooleanField(default=False, verbose_name="Réalisé")),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectifs",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OffreEmploi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Titre de l'offre"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "date_publication",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "cloturee",
                    models.BooleanField(default=False, verbose_name="Clôturée"),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("cv", models.FileField(upload_to="cvs/", verbose_name="CV")),
                (
                    "lettre_motivation",
                    models.TextField(blank=True, verbose_name="Lettre de motivation"),
                ),
                (
                    "statut",
                    models.CharField(
                        default="Nouveau", max_length=50, verbose_name="Statut"
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="employees.offreemploi",
                        verbose_name="Offre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("heure_arrivee", models.TimeField(verbose_name="Heure d'arrivée")),
                (
                    "heure_depart",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de départ"
                    ),
                ),
                (
                    "heures_sup",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        verbose_name="Heures supplémentaires",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                ("motif", models.CharField(max_length=200, verbose_name="Motif")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primes_recues",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contrats/",
                        verbose_name="Fichier du contrat",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="employees.employe",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "type_contrat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.typecontrat",
                        verbose_name="Type de contrat",
                    ),
                ),
            ],
        ),
    ]
