# Generated by Django 6.0.1 on 2026-01-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_formation_typecontrat_departement_manager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conge",
            name="validateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conges_a_valider",
                to="employees.employe",
                verbose_name="À l'attention de (Manager)",
            ),
        ),
    ]
