# Generated by Django 6.0.1 on 2026-01-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_conge_validateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departement",
            name="manager",
        ),
    ]
