# Generated by Django 6.0.1 on 2026-02-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_departement_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('RH', 'Responsable RH'), ('MANAGER', 'Chef Service'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=20, verbose_name='Rôle'),
        ),
    ]
