# Generated by Django 6.0.1 on 2026-02-07 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employe_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='chef_de_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_dirige', to='employees.employe', verbose_name='Chef de service'),
        ),
    ]
