# Generated by Django 6.0.1 on 2026-02-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_departement_chef_de_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="formations",
                to="employees.departement",
                verbose_name="Département",
            ),
        ),
    ]
